import type { Destination, DestinationDetail } from "@/types";

export const MOCK_DESTINATIONS: Destination[] = [
  // ── 1~2박 권장 (비행 ~2.5h) ──────────────────────
  {
    id: "osaka",
    city: "오사카",
    cityEn: "Osaka",
    country: "일본",
    countryCode: "JP",
    region: "asia",
    emoji: "🏯",
    imageUrl: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=430&h=280&fit=crop&auto=format&q=80",
    temperature: 14,
    reason: "인천에서 2시간 거리. 도톤보리 야경, 타코야키, 유니버설 스튜디오. 짧은 일정에 꽉 찬 일본 여행",
    tags: ["미식", "야경", "근거리"],
    flightHoursFromKorea: 2,
    minRecommendedNights: 1,
  },
  {
    id: "tokyo",
    city: "도쿄",
    cityEn: "Tokyo",
    country: "일본",
    countryCode: "JP",
    region: "asia",
    emoji: "🗼",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=430&h=280&fit=crop&auto=format&q=80",
    temperature: 8,
    reason: "봄 벚꽃·가을 단풍 시즌 최고. 교통이 편리하고 미식·쇼핑·문화가 집약된 도시",
    tags: ["벚꽃", "미식", "교통 편리"],
    flightHoursFromKorea: 2.5,
    minRecommendedNights: 1,
    isNew: true,
  },
  // ── 2~3박 권장 (비행 3~5h) ──────────────────────
  {
    id: "hongkong",
    city: "홍콩",
    cityEn: "Hong Kong",
    country: "홍콩",
    countryCode: "HK",
    region: "asia",
    emoji: "🌆",
    imageUrl: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=430&h=280&fit=crop&auto=format&q=80",
    temperature: 22,
    reason: "마천루와 야경, 세계 최고 수준의 딤섬. 2박이면 알차게 즐길 수 있는 콤팩트 도시",
    tags: ["야경", "딤섬", "쇼핑"],
    flightHoursFromKorea: 3.5,
    minRecommendedNights: 2,
  },
  {
    id: "danang",
    city: "다낭",
    cityEn: "Da Nang",
    country: "베트남",
    countryCode: "VN",
    region: "asia",
    emoji: "🏖️",
    imageUrl: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=430&h=280&fit=crop&auto=format&q=80",
    temperature: 26,
    reason: "미케 비치와 호이안 구시가지. 저렴한 물가와 맛있는 음식. 짧은 해변 휴양 최적",
    tags: ["해변", "호이안", "저물가"],
    flightHoursFromKorea: 4.5,
    minRecommendedNights: 2,
  },
  // ── 3~4박 권장 (비행 5~7h) ──────────────────────
  {
    id: "bangkok",
    city: "방콕",
    cityEn: "Bangkok",
    country: "태국",
    countryCode: "TH",
    region: "asia",
    emoji: "⛩️",
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c8dd0d5?w=430&h=280&fit=crop&auto=format&q=80",
    temperature: 28,
    reason: "겨울에도 따뜻한 28°C. 화려한 사원·야시장·마사지. 최소 3박은 있어야 제대로 즐길 수 있는 도시",
    tags: ["겨울 따뜻", "야시장", "사원"],
    flightHoursFromKorea: 5.5,
    minRecommendedNights: 3,
  },
  {
    id: "singapore",
    city: "싱가포르",
    cityEn: "Singapore",
    country: "싱가포르",
    countryCode: "SG",
    region: "asia",
    emoji: "🦁",
    imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=430&h=280&fit=crop&auto=format&q=80",
    temperature: 30,
    reason: "마리나 베이 샌즈, 가든스 바이 더 베이. 세계 최고 수준의 음식과 청결함. 환승 여행에도 최적",
    tags: ["야경", "미식", "도시국가"],
    flightHoursFromKorea: 6.5,
    minRecommendedNights: 3,
  },
  // ── 4~5박 권장 (비행 7h) ────────────────────────
  {
    id: "bali",
    city: "발리",
    cityEn: "Bali",
    country: "인도네시아",
    countryCode: "ID",
    region: "asia",
    emoji: "🌴",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=430&h=280&fit=crop&auto=format&q=80",
    temperature: 30,
    reason: "열대 리조트와 힌두 사원이 어우러진 힐링 여행지. 편도 7시간 비행 — 4박 이상 일정에 적합",
    tags: ["리조트", "힐링", "열대"],
    flightHoursFromKorea: 7,
    minRecommendedNights: 4,
  },
  // ── 5~6박 권장 (비행 10h) ──────────────────────
  {
    id: "sydney",
    city: "시드니",
    cityEn: "Sydney",
    country: "호주",
    countryCode: "AU",
    region: "oceania",
    emoji: "🦘",
    imageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=430&h=280&fit=crop&auto=format&q=80",
    temperature: 24,
    reason: "오페라 하우스와 본다이 비치. 12~2월은 남반구 여름. 편도 10시간 — 5박 이상 일정 권장",
    tags: ["오세아니아", "해변", "남반구 여름"],
    flightHoursFromKorea: 10,
    minRecommendedNights: 5,
  },
  // ── 6박+ 권장 (비행 12~14h) ────────────────────
  {
    id: "prague",
    city: "프라하",
    cityEn: "Prague",
    country: "체코",
    countryCode: "CZ",
    region: "europe",
    emoji: "🏰",
    imageUrl: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=430&h=280&fit=crop&auto=format&q=80",
    temperature: 5,
    reason: "유럽에서 물가가 가장 저렴한 중세 도시. 구시가지 야경이 압도적. 편도 13시간 — 6박 이상 필수",
    tags: ["저물가", "중세", "야경"],
    flightHoursFromKorea: 13,
    minRecommendedNights: 6,
  },
  {
    id: "barcelona",
    city: "바르셀로나",
    cityEn: "Barcelona",
    country: "스페인",
    countryCode: "ES",
    region: "europe",
    emoji: "🎨",
    imageUrl: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=430&h=280&fit=crop&auto=format&q=80",
    temperature: 22,
    reason: "가우디 건축과 지중해 해변. 여름 성수기 방문 추천. 편도 13시간 비행 — 충분한 체류 시간이 필요",
    tags: ["지중해", "건축", "여름"],
    flightHoursFromKorea: 13,
    minRecommendedNights: 6,
  },
];

export function getFilteredByNights(nights: number): Destination[] {
  return MOCK_DESTINATIONS.filter((d) => d.minRecommendedNights <= nights);
}

export const MOCK_DETAIL: DestinationDetail = {
  destination: MOCK_DESTINATIONS.find((d) => d.id === "bangkok")!,
  weather: {
    temperature: 28,
    feelsLike: 32,
    description: "맑음",
    humidity: 65,
    icon: "01d",
    isRainySeason: false,
  },
  exchange: {
    currency: "THB",
    currencyName: "태국 바트",
    ratePerKRW: 38.2,
    symbol: "฿",
  },
  places: [
    { name: "왓 프라깨우", category: "사원", description: "방콕 왕궁 내 황금 사원, 태국 최고의 성지", rating: 4.8 },
    { name: "왓 포", category: "사원", description: "거대한 와불상으로 유명한 방콕 최고 사원", rating: 4.7 },
    { name: "카오산 로드", category: "거리", description: "배낭여행자의 성지, 야시장과 나이트라이프", rating: 4.3 },
    { name: "차투착 주말시장", category: "시장", description: "세계 최대 규모 야외 시장, 8,000개 매장", rating: 4.6 },
    { name: "아시아티크", category: "쇼핑", description: "짜오프라야 강변 야외 쇼핑몰·야시장 복합", rating: 4.5 },
  ],
  tips: [
    { category: "clothing", content: "28~33°C 열대 기후. 반소매 기준이나 사원 방문 시 어깨·무릎 가리는 옷 필수" },
    { category: "transport", content: "BTS 스카이트레인·MRT 지하철 활용. 택시는 미터기 사용 확인 필수" },
    { category: "safety", content: "귀중품 분산 보관, 툭툭 바가지 주의. 음수는 생수 구매 권장" },
    { category: "culture", content: "사원에서 신발 벗기, 국왕 관련 언급 주의 (불경죄 법률 존재)" },
    { category: "budget", content: "길거리 음식 40~80바트, 편의점 식사 100바트 수준으로 저렴" },
  ],
};
